### ISSUE TITLE
32bit address?

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [nopnop2002/esp-idf-24c#5]
Hi,
For my application, i need 32bit addressing (uint32_t) for the eeprom. How do I do this? Iam using an 24C256 EEPROM

**Comment by nopnop2002** [comment]
I don't understand your question.

The maximum Address for 24c256 is 0x7FFF.

ReadRom(&dev, (uint16_t)data_addr, data);
WriteRom(&dev, (uint16_t)data_addr, data);

**Comment by ElectroBoy404NotFound** [comment]
Sorry, i thought the size of 25q256 and 24c256 are the same
